### ISSUE TITLE
Work with CNCF to enable Google groups on KubeVirt account

### ISSUE THREAD

**Issue by mazzystr** [kubevirt/community#107]
CNCF KubeVirt account currently cannot create Google groups

Please work with CNCF to enable Google groups creation for KubeVirt account

**Comment by jberkus** [comment]
I'll ask how this is supposed to work.  Currently we can create groups, and then transfer them to kubevirt@cncf.io ownership, but that's not ideal.

**Comment by jberkus** [comment]
Hey, closing this because we're not going to be creating google groups, and we have a different process for requesting mailing lists from CNCF.
