### ISSUE TITLE
KubeCon 2021 NA conference

### ISSUE THREAD

**Issue by davidvossel** [kubevirt/community#109]
# KubeCon 2021 North America
CFP: [link](https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/program/cfp/ )

**Status:** Submitted, waiting on review

# Proposal to present KubeCon 2021 NA

Presenter: @rthallisey 
Presenter: @davidvossel 

**General Topic Idea** Ryan and I want to present the journey of how we measured and improved KubeVirt's performance at scale. This will include details into how we approached scale testing along with how we profiled the distributed system to evaluate and improve performance. 

**Title:** 1000s of VMs and beyond: KubeVirt performance and scale

**Abstract:**

Our goal is to scale KubeVirt to new levels and measure its performance and efficiency; here’s our journey to 1000s of VMs:

In this session we will uncover the tools and methodologies we used to visualize, measure, and identify KubeVirt performance bottlenecks and improve them. We'll outline how we collected baseline performance metrics under load and how changing certain code paths impacted baseline performance. From our learnings, we hope you’ll come away with an understanding of what patterns can help improve performance in your own Kubernetes controllers as well as an understanding of how to approach profiling a distributed control plane.

**Comment by jberkus** [comment]
This got submitted, right?  Due date was Sunday.

**Comment by jberkus** [comment]
Can we alter this slightly and submit it to KVMforum ASAP?

**Comment by davidvossel** [comment]
> This got submitted, right? Due date was Sunday.

yes, i submitted it to KubeCon NA 2021

> Can we alter this slightly and submit it to KVMforum ASAP?

I didn't submit to kvm forum. It's unclear how relevant this topic is to that conference. When i look at typical talks there, they focus on the layer below the scale performance we'd be discussing. We'd be focusing on how well the kubevirt control plane scales, which doesn't have much to do with KVM itself.

**Comment by jberkus** [comment]
This seems resolved, no?

/close
