### ISSUE TITLE
Scale missing from sigs.yaml

### ISSUE THREAD

**Issue by mazzystr** [kubevirt/community#140]
/kind bug

Please update sigs.yaml @rthallisey

**Comment by rthallisey** [comment]
What needs to change?  There's a section in `sig-scale` in https://github.com/kubevirt/community/blob/main/sigs.yaml#L85

**Comment by mazzystr** [comment]
Oh dang.  We didn't see it yesterday when looking for all the sigs for
incubation DD.

Sorry to bother you.  Closing.

/close
