### ISSUE TITLE
[devconf.cz] Intro to KubeVirt + Katacoda scenario demo

### ISSUE THREAD

**Issue by mazzystr** [kubevirt/community#145]
What: https://devconf.cz
When: Jan 28-29, 2022
Where: Brno, Czech Republic
CFP: https://cfp.devconf.info/login

**Comment by alicefr** [comment]
The talk hasn't been accepted

**Comment by alicefr** [comment]
We can close this issue

**Comment by mazzystr** [comment]
:(
