### ISSUE TITLE
Generic background image

### ISSUE THREAD

**Issue by fabiand** [kubevirt/community#16]
Sometimes, i.e. for twitter or for the youtube channel - a generic background image is needed as a header or footer.

https://www.youtube.com/channel/UC2FH36TbZizw25pVT1P3C3g/
https://twitter.com/kubevirt

it would be nice to have a simple themed background image which can be used here and there.

**Comment by mindreeper2420** [comment]
I've reached out to UXD to see what can be designed to match the new design of KubeVirt.io.

**Comment by serenamarie125** [comment]
@fabiand I'll get someone assigned to this
