### ISSUE TITLE
How do I join the kubevirt slack?

### ISSUE THREAD

**Issue by zhangylc2020** [kubevirt/community#173]

**Comment by mazzystr** [comment]
Hi @zhangylc2020 Can you browse to https://kubevirt.io then click on the Community button.  Follow directions there.

Do let us know if you still have trouble.  We can take further action such as clarify that page or add a footer to emails on the kubevirt-dev mailing list.

Thanks!

**Comment by zhangylc** [comment]
> Hi @zhangylc2020 Can you browse to https://kubevirt.io then click on the Community button. Follow directions there.
> 
> Do let us know if you still have trouble. We can take further action such as clarify that page or add a footer to emails on the kubevirt-dev mailing list.
> 
> Thanks!


> Hi @zhangylc2020 Can you browse to https://kubevirt.io then click on the Community button. Follow directions there.
> 
> Do let us know if you still have trouble. We can take further action such as clarify that page or add a footer to emails on the kubevirt-dev mailing list.
> 
> Thanks!

I've joined kubevirt slack. Thanks.

**Comment by mazzystr** [comment]
Great, I'm glad our process still works. Thanks for joining us.  :)

/close
