### ISSUE TITLE
[GSoc] Create KubeVirt seccomp profiles

### ISSUE THREAD

**Issue by alicefr** [kubevirt/community#205]
# Title: Create KubeVirt seccomp profiles
## Description:
[Seccomp](https://man7.org/linux/man-pages/man2/seccomp.2.html) is a security facility from the Linux Kernel that prevents processes to execute unauthorized syscalls.  By limiting the number of permitted syscalls, seccomp is being utilized in conjunction with [Kubernetes](https://kubernetes.io/docs/tutorials/security/seccomp/) to reduce the attack surface of the containers.
Container engines offer their own default profile. However, we cannot assume that one size fits all. Therefore, the default profile may either permit syscalls that are in fact not required by the workload or prohibit legitimate syscalls.

## Expected outcome:
Seccomp custom profiles are already supported by KubeVirt, although they are still based on the cri-o seccomp profile. The goal of this internship is to integrate and automate the syscall auditing during testing, then utilize the test results to create a seccomp profile with the syscalls actually used at runtime. Finally, the seccomp profile will be applied to the test suite to ensure that it does not block any needed syscalls.

As an optional addition, the intern could look into if various seccomp profiles can be applied depending on the feature specified by the Virtual Machine description if the project's time constraints permit it.

### Links:
[Seccomp Linux man page](https://man7.org/linux/man-pages/man2/seccomp.2.html)
[Kubernetes with seccomp](https://kubernetes.io/docs/tutorials/security/seccomp/)
[Seccomp profile for KubeVirt](https://github.com/kubevirt/kubevirt/pull/8917)

### How to start

**Have a good development environment**
For this project is highly recommended to have available a Linux machine with KVM (e.g try to validate the environment using `virt-host-validate`).

**Where to look first**:
The first document to check if for sure the [getting started docs](https://github.com/kubevirt/kubevirt/blob/main/docs/getting-started.md) and get familiar with how to create a k8s cluster with kubevirt and starting some VMs using the [examples](https://github.com/kubevirt/kubevirt/tree/main/examples).  An other great source is the [katacoda scenarios](https://github.com/kubevirt/katacoda-scenarios)

**Specifically to this project**:
For this particular task, it is important to get familiar how KubeVirt works and understand how it creates the pods where the VMs are launched (e.g https://github.com/kubevirt/kubevirt/tree/main/pkg/virt-controller/services)

Also having an idea of how the development and CI environment [kubevirtci](https://github.com/kubevirt/kubevirtci) work will be fundamental for solving the task. For example, try to understand how the [functional tests](https://github.com/kubevirt/kubevirt/tree/main/tests) work and are deployed.

It will also be important to understand how Kubernetes uses [seccomp](https://kubernetes.io/docs/tutorials/security/seccomp/). For sure a good exercise for your knowledge is to try the examples listed in the documentation and try to log the syscalls your application executes

Feel free to ask questions in our [slack channel](https://kubernetes.slack.com/archives/C0163DT0R8X) (@xpivarc & Alice Frosi should be our nicks), this will be a great start to get in touch with the community.

We also have community meetings on Wednesday (see https://github.com/kubevirt/community/#socializing) and another great place where to ask questions.

If you have time and want a first-hand experience with KubeVirt check our [`good-first-issue`](https://github.com/kubevirt/kubevirt/labels/good-first-issue) list. This isn't mandatory for participating in the project, but just a suggestion.

However, keep in mind that at the end you need to write a proposal for this project, and we can help you review it. For more general guidance, please check the [gsoc documentation](https://google.github.io/gsocguides/student/writing-a-proposal).

### How and where to ask questions ###
First, try to check [KubeVirt documentation](https://github.com/kubevirt/kubevirt/tree/main/docs), we cover many topics and you might already find some of the answers. If there is something unclear, feel free to open an issue and a PR. This is already a great start to getting in touch with the process.

For questions related to KubeVirt and not strictly to the GSoc program, try to use the [slack channel](https://kubernetes.slack.com/archives/C0163DT0R8X) and the [issues](https://github.com/kubevirt/kubevirt/issues) as much as possible. Your question can be useful for other people, and the mentors might have a limited amount of time.

If something doesn't work, try to document the steps and how to reproduce the issue as clearly as possible. The more information you provide the easiest is for us to help you. If you open an issue in KubeVirt, this already guides you with a template with the kind of information we generally need.

### How to send your proposal for review
The preferred way is to create a google doc and share it with both mentors (slack or email work). If for any reason, google doc doesn't work for you, please share your proposal by email.

Project size: 12 weeks
Required skills: Kubernetes knowledge
Desirable skills: Virtualization and GoLang programming skills
Mentor: Alice Frosi <afrosi@redhat.com>, Co-mentor: Luboslav Pivarc <lpivarc@redhat.com>

**Comment by alicefr** [comment]
@aburdenthehand is this issue here fine for you?

**Comment by Chinwendu20** [comment]
Hello please I would like to clarify if this is a 350 hour or 175 hour question

**Comment by alicefr** [comment]
@Chinwendu20 you are right, this isn't clear from the description. Generally, the projects should be 350 hours, but in particular the first part of this one, I think could be achieved within 175 hours if correctly planned. We should also wait  for @aburdenthehand confirmation. He's out, we should have an answer when he's back

**Comment by i-am-yuvi** [comment]
Hey, I am interested in this project. I have also contributed to many open-source projects. May I know some references to get started?

**Comment by ratul-07** [comment]
Hello, I am interested in this project as a part of GSoc 23. Could ypu please point me to some resources to get to know more about this project?

**Comment by ameyanator** [comment]
Hi, I am interested to contribute for this project in GSoC 2023. I have good development experience in Golang. Could the community share if there are any onboarding docs or references to get started with Kubevirt?

**Comment by octonawish-akcodes** [comment]
I am interested in this

**Comment by aburdenthehand** [comment]
@Chinwendu20 @alicefr 
Thanks for your interest! Please note that I will be more available from next week. 
Re: size of project. My understanding is that this is best determined by contributors after consultation with mentors when designing their project plan. I would treat is as a large project (350 hours) to start with as it is possible to shrink a scope after it has begun but not to grow. Hope that helps!
And just in case you haven't seen, there's some really useful information in the GSOC student guide: https://google.github.io/gsocguides/student/

**Comment by alicefr** [comment]
**Where to look first**:
The first document to check if for sure the [getting started docs](https://github.com/kubevirt/kubevirt/blob/main/docs/getting-started.md) and get familiar to create a k8s cluster with kubevirt and starting some VMs using the [examples](https://github.com/kubevirt/kubevirt/tree/main/examples).  An other great source is the [katacoda scenarios](https://github.com/kubevirt/katacoda-scenarios)

**Specifically to this project**:
For this particular task, it is important to get familiar how KubeVirt works and understand how it creates the pods where the VMs are launched (e.g https://github.com/kubevirt/kubevirt/tree/main/pkg/virt-controller/services)
Also understanding how the development and CI environment [kubevirtci](https://github.com/kubevirt/kubevirtci) work will be fundamental for solving the task. For example, try to understand how the [functional tests](https://github.com/kubevirt/kubevirt/tree/main/tests) work and are deployed.
Additionally, it will be important also to understand how Kubernetes uses [seccomp](https://kubernetes.io/docs/tutorials/security/seccomp/). For sure a good exercise for your understanding is to try the examples listed in the documentation and try to log the syscalls your application executes

Feel free to ask questions in our [slack channel](https://kubernetes.slack.com/archives/C0163DT0R8X) (@xpivarc & Alice Frosi should be our nicks), this will be a great start to get in touch with the community.

We also have community meetings on Wednesday (see https://github.com/kubevirt/community/#socializing) and another great place where to ask questions.

Keep in mind that at the end you need to write a proposal for this project, and we can help you in reviewing it. For more general guidance, please check the [gsoc documentation](https://google.github.io/gsocguides/student/writing-a-proposal).

**Comment by aryankaushik-git** [comment]
Hi @alicefr, this is Aryan from INDIA, I'm looking forward to Contribute in KubeVirt for my GSOC project. Thanks for sharing the docs and other details, I'll go through them and let know my progress.

**Comment by dev-divyansh** [comment]
Hello @alicefr  I am interested and excited to work on this ;;  i am going through the docs you shared and will let you know soon

**Comment by alicefr** [comment]
hi everyone, we just realized that we are missing how you can send us your proposal for review. The easiest way will be for us that you create a google doc document and you will share it with us (email or slack). If for any reasons, google doc doesn't work for you, just share it via email with me and Lubo, you find our email address in the description above. I'll add this information in the description above

**Comment by Vikash993468** [comment]
Hii @alicefr @aburdenthehand  ,I am interested and looking forward to contribute in this project...i visited this page last week and started exploring about what you mentioned in the "How to start" section ,right now i have basic understanding of the above mentioned thing like how to run VMs on K8s with kubevirt ,how kubevirt components create the pods,why restricting some of the syscalls is necessary and then how K8s lets us automatically apply the seccomp profiles (which was copied to the nodes) to the pods and containers.Some of the queries regarding the expected outcomes (which is  mentioned above) is :

1) How to test the syscall auditing and then how do we precisely know which syscalls should be allowed/deny/audit ,so that we can create seccomp profile ?? I couldn't find any resource for that.

One more issue is I am not able to join the slack channel (whats the channel name??)
Thanks

**Comment by ShivangShandilya** [comment]
This project intrigues me greatly. I have a good knowledge of Kubernetes and as mentioned above I took a look at how this all works on KubeVirt. The only issue is I don't have a Linux machine, is it possible to work on this project without it?

**Comment by alicefr** [comment]
This is a kind reminder that next week (April 4) the application period ends. If any of you want a last review of the proposal, now is a good time. Please, ping us if you need some help.

**Comment by xpivarc** [comment]
This is the last reminder that every application needs to go through GSoc official channels ([link](https://summerofcode.withgoogle.com/programs/2023)). We should wrap up reviews today which should leave some time for everybody before final submission.

**Comment by sudo-NithishKarthik** [comment]
https://github.com/sudo-NithishKarthik/k8s_seccomp_generator/

**Comment by alicefr** [comment]
The project has been successfully completed and the work is available under: https://github.com/kubevirt/k8s-seccomp-generator
