### ISSUE TITLE
Require signoffs for web commits organization-wide

### ISSUE THREAD

**Issue by cwilkers** [kubevirt/community#211]
I would like to enable the requirement of signoffs for web based commits for at least all the web and community repositories in the org. We often run into the case where a documentation review contains suggested fixes, that, if the original author is caught unaware, can turn into an unsigned commit, and block a PR from merging, forcing the author to do some arcane git commit amendments and/or squash rebases followed by a force push to fix.

Per [this GitHub blog entry](https://github.blog/changelog/2022-06-08-admins-can-require-sign-off-on-web-based-commits/), there is now a feature available to enable DCO signoffs for commits made through the web interface.

There are two ways to handle this, it can be set on an organization level, affecting all repositories, or on a repo by repo level. Looking at our existing peribolos setup in [project-infra](https://github.com/kubevirt/project-infra/) there isn't an obvious example of us engaging this setting.

I would like to ask for help from somebody who understands Peribolos better to figure out the right place for this setting, and also the right scope.

In the [GitHub REST API docs](https://docs.github.com/en/rest/orgs/orgs?apiVersion=2022-11-28#update-an-organization) there is a parameter, `web_commit_signoff_required` that appears to work either in the org or the repo context.

If Peribolos works by translating the [orgs.yaml](https://github.com/kubevirt/project-infra/blob/main/github/ci/prow-deploy/files/orgs.yaml) directly into REST API requests, then a newer feature like this one will not require direct support from the tool and should "just work". If not, hopefully a bad parameter would not cause any issues.

**Comment by dhiller** [comment]
There's a presubmit called `pull-kubevirt-org-github-config-updater` that checks whether the configuration of an `orgs.yaml` is valid, so as a first try you could just change the repo config and see whether that one complains.

Other than that the [docs](https://docs.prow.k8s.io/docs/components/cli-tools/peribolos/) for `peribolos` are a bit sparse, I couldn't find much about repo configuration, will need to dig into the source code at [test-infra](https://github.com/kubernetes/test-infra/blob/3fddbc7d9ed76720801c199f85d0c69449609162/prow/cmd/peribolos/main.go#L976).

**Comment by dhiller** [comment]
From what I remember the authors have a struct mapping defined that translates into the yaml. I guess that might be the way to add the flag on org and/org repo level.

**Comment by dhiller** [comment]
So IIUC correctly peribolos does not (yet) support that setting. But I think that we can just enable it if it is helpful. 

I have not been aware that users are actually using the web interface to edit files in KubeVirt org, but I'd find it helpful.

**Comment by cwilkers** [comment]
Closing since this was fixed org-wide and works now.
