### ISSUE TITLE
Create default community health files

### ISSUE THREAD

**Issue by dhiller** [kubevirt/community#235]
According to the [GitHub docs](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file) there's a mechanism to provide defaults for CONTRIBUTING, ISSUE_TEMPLATE etc.

This way we may streamline everything on standard files and do changes only in one place. If required, repos can still differ and use their own files.

Side note: this could very well make #103 obsolete.

FYI @aburdenthehand @fabiand

**Comment by aroramrinaal** [comment]
hey @dhiller , I would like to take up this issue.

**Comment by dhiller** [comment]
Hey @aroramrinaal, thank you at first for your interest in this!

@aburdenthehand how about we give this a try?

**Comment by aburdenthehand** [comment]
Great idea @dhiller, thanks for raising this.
And thank you @aroramrinaal for taking this on!

**Comment by dhiller** [comment]
> @dhiller: Can not set label good-first-issue: Must be member in one of these teams: [kubevirtorg-label]

Meh. @aburdenthehand would I be eligible for adding `good-first-issue` to community repo from your POV?

**Comment by aburdenthehand** [comment]
@dhiller - yes to both. I actually wasn't aware that repo approvers couldn't apply labels.

**Comment by dhiller** [comment]
> @dhiller - yes to both. I actually wasn't aware that repo approvers couldn't apply labels.

Luckily this is only true for the good-first-issue label, since it is restricted. The other labels can be applied as usual, i.e. via `sig|area|type` command.

**Comment by aburdenthehand** [comment]
/remove-lifecycle stale
@aroramrinaal Is this still something you're interested in working on?

**Comment by OPC-16** [comment]
Hey @dhiller and @aburdenthehand, I read the [github docs](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file) and it is mentioned [here](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file#creating-a-repository-for-default-files) the process of creating a repo for default files.

So, what we want to achieve is that we create a .github named repo and put/create following files there
* [governance](https://github.com/kubevirt/community/blob/main/GOVERNANCE.md)
* Code of Conduct, either [this](https://github.com/kubevirt/kubevirt/blob/main/CODE_OF_CONDUCT.md) or [this](https://github.com/kubevirt/community/blob/main/code-of-conduct.md)
* [contributing](https://github.com/kubevirt/kubevirt/blob/main/CONTRIBUTING.md)
* [security](https://github.com/kubevirt/kubevirt/blob/main/SECURITY.md)
* pull request and issue templates like [here](https://github.com/kubevirt/kubevirt/tree/main/.github), (but I think this would be specific to each repo)

And with this we only need to perform changes in a single place. Am I right?

**Comment by dhiller** [comment]
> Hey @dhiller and @aburdenthehand, I read the [github docs](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file) and it is mentioned [here](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file#creating-a-repository-for-default-files) the process of creating a repo for default files.

Yes.
> 
> So, what we want to achieve is that we create a .github named repo and put/create following files there
> 
> * [governance](https://github.com/kubevirt/community/blob/main/GOVERNANCE.md)
> * Code of Conduct, either [this](https://github.com/kubevirt/kubevirt/blob/main/CODE_OF_CONDUCT.md) or [this](https://github.com/kubevirt/community/blob/main/code-of-conduct.md)
> * [contributing](https://github.com/kubevirt/kubevirt/blob/main/CONTRIBUTING.md)
> * [security](https://github.com/kubevirt/kubevirt/blob/main/SECURITY.md)
> * pull request and issue templates like [here](https://github.com/kubevirt/kubevirt/tree/main/.github), (but I think this would be specific to each repo)
> 
> And with this we only need to perform changes in a single place. Am I right?

Yes. Currently we create new repositories by a PR[^1] against `orgs.yaml` in `kubevirt/project-infra` repo. This would be the first step. Please add @brianmcarey and @dhiller to the team created in that PT.

[^1]: https://github.com/kubevirt/project-infra/pull/990/files

**Comment by dhiller** [comment]
@OCP-16 I should add that you can take most, if not all of the files from the `kubevirt/kubevirt` repository, or if there is something missing, from `kubevirt/community`

**Comment by dhiller** [comment]
@@OPC-16 ^^

**Comment by OPC-16** [comment]
Hey @dhiller, thanks for replying. 

> Currently we create new repositories by a PR against **orgs.yaml** in **kubevirt/project-infra** repo. This would be the first step.

ok.

So, now I will create a PR in `kubevirt/project-infra` repo. But do I need to create an issue in the project-infra repo first or should I just mention this current issue there?

And following should be the changes in the [`orgs.yaml`](https://github.com/kubevirt/project-infra/blob/main/github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml) file, right?
```yaml
.github:
   description: Default Community health files
   team: 
      -  brianmcarey
      -  dhiller
```

**Comment by OPC-16** [comment]
> Please add @brianmcarey and @dhiller to the team created in that PT.

you meant to add in [this](https://github.com/kubevirt/project-infra/blob/main/github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml#L588) teams right? and not just below the description in above snippet

```yaml
.github:
   description: Default Community health files
```

```yaml
teams:
   community-health-files:
      description: manage default community health files
      maintainers: 
           - brianmcarey 
           - dhiller 
      repos:
          .github
```

**Comment by OPC-16** [comment]
sorry, I am new so don't know much

**Comment by dhiller** [comment]
> sorry, I am new so don't know much

No worries. I think I didn't explain it well enough, so I'll try to do better now.

As a background: we use periodic runs of peribolos to keep the state of our GitHub org in sync, with orgs.yaml being the configuration file describing how our org should look like. [^1]

This yaml file has sections that define the org, it's repositories and it's teams. What we need for a new repo is two changes
1. a new entry below the `repos:` section, and 
2. another one below the `teams:` section that defines the access to the repository.

The former could use, as you already added above, a good `description` entry that tells us what the repository actually is for, where the latter, as you already wrote, should contain @dhiller and @brianmcarey as `maintainers`.

Please ping me if you have any further questions.

[^1]: https://github.com/kubevirt/community/blob/main/docs/automating-github-org-management.md

**Comment by dhiller** [comment]
One more note: just try to create a PR with the changes, the checks will tell you whether you made any mistakes.

**Comment by OPC-16** [comment]
Thanks @dhiller for the guidance. I will create the PR.

**Comment by dhiller** [comment]
/unassign @aroramrinaal 
/assign @OPC-16 

Hey @OPC-16 I think this issue is done, so I am closing it!

/close

Would you mind taking a look at the work that is eventually remaining? If this is not done, you are free to reopen it. Or just ping me and I'll do it.
