### ISSUE TITLE
devstats,repo_groups: update procedure to sync CNCF devstats

### ISSUE THREAD

**Issue by dhiller** [kubevirt/community#330]
**What happened**:

A job is triggered after every update to sigs.yaml, creating a PR against CNCF devstats in order to keep the repo groups in sync - job history: https://prow.ci.kubevirt.io/job-history/gs/kubevirt-prow/logs/postsubmit-community-update-kubevirt-devstats-repo-sql

Now it seems that updates to the structure have happened which we haven't been aware of, as noted in a PR review comment by @lukaszgryglicki from May 2024 [1] , where he requested to update the process to use the new structure. This likely requires updating the script [hack/generate-devstats-repo-sql.py](https://github.com/kubevirt/community/blob/main/hack/generate-devstats-repo-sql.py) which lives in k/community repo to the latest version which should reside somewhere around github.com/cncf/devstats/scripts (don't remember exactly where that was right now). 

After that following generated PRs have been closed [2] since the issue has not been handled as requested. 

**What you expected to happen**:
* devstats repo groups update procedure should have gotten updated to use the new procedure
* we should have had a process to take a look at the created PRs and see whether they got merged
* we should have had a process to check procedure updates (likely check whenever the source script has received updates)

**How to reproduce it (as minimally and precisely as possible)**:
See PR comment.

**Additional context**:

[1]: https://github.com/cncf/devstats/pull/59#pullrequestreview-1991622069
[2]: https://github.com/cncf/devstats/pulls?q=sort%3Aupdated-desc+is%3Apr+author%3Akubevirt-bot

**Comment by lukaszgryglicki** [comment]
Basically we now use `gha_repo_groups` table instead of gha_repos which allows single repo to belong to multiple groups in addtion to multiple repos belonging to a single group (so this is `N:M` relation now).

But columns are almost the same - just take a look at any `scripts/*/repo_groups.sql` example.

Table `gha_repos` structure is:
```
\d gha_repos
                          Table "public.gha_repos"
    Column    |            Type             | Collation | Nullable | Default 
--------------+-----------------------------+-----------+----------+---------
 id           | bigint                      |           | not null | 
 name         | character varying(160)      |           | not null | 
 org_id       | bigint                      |           |          | 
 org_login    | character varying(100)      |           |          | 
 repo_group   | character varying(80)       |           |          | 
 alias        | character varying(160)      |           |          | 
 license_key  | character varying(30)       |           |          | 
 license_name | character varying(160)      |           |          | 
 license_prob | double precision            |           |          | 
 created_at   | timestamp without time zone |           |          | now()
 updated_at   | timestamp without time zone |           |          | now()
Indexes:
    "gha_repos_pkey" PRIMARY KEY, btree (id, name)
    "repos_alias_idx" btree (alias)
    "repos_created_at_idx" btree (created_at)
    "repos_id_idx" btree (id)
    "repos_license_key_idx" btree (license_key)
    "repos_license_name_idx" btree (license_name)
    "repos_license_prob_idx" btree (license_prob)
    "repos_name_idx" btree (name)
    "repos_org_id_idx" btree (org_id)
    "repos_org_login_idx" btree (org_login)
    "repos_repo_group_idx" btree (repo_group)
    "repos_updated_at_idx" btree (updated_at)
```


Table `gha_repo_groups` structure is:
```
\d gha_repo_groups
                    Table "public.gha_repo_groups"
   Column   |          Type          | Collation | Nullable | Default 
------------+------------------------+-----------+----------+---------
 id         | bigint                 |           | not null | 
 name       | character varying(160) |           | not null | 
 repo_group | character varying(80)  |           | not null | 
 org_id     | bigint                 |           |          | 
 org_login  | character varying(100) |           |          | 
 alias      | character varying(160) |           |          | 
Indexes:
    "gha_repo_groups_pkey" PRIMARY KEY, btree (id, name, repo_group)
    "repo_groups_alias_idx" btree (alias)
    "repo_groups_id_idx" btree (id)
    "repo_groups_name_idx" btree (name)
    "repo_groups_org_id_idx" btree (org_id)
    "repo_groups_org_login_idx" btree (org_login)
    "repo_groups_repo_group_idx" btree (repo_group)
```

**Comment by dhiller** [comment]
@lukaszgryglicki so just to validate with you: IIUC I can create a new template based on [`scripts/shared/repo_groups.sql` from cncf/devstats](https://github.com/cncf/devstats/blob/master/scripts/shared/repo_groups.sql) where I after the insertions into gha_repo_groups I would do something like this 

```sql
...

insert into gha_repo_groups(id, name, alias, repo_group, org_id, org_login) select id, name, alias, org_login, org_id, org_login from gha_repos where org_id is not null and org_login is not null and trim(org_login) != '' on conflict do nothing;


-- Per each SIG that has claimed ownership via one of it's subprojects we add a new entry in gha_repo_groups

-- 1)
insert into gha_repo_groups(id, name, repo_group, alias, org_id, org_login)
select id, name, 'sig-documentation', alias, org_id, org_login 
  from gha_repo_groups
 where lower(name) in (
         'kubevirt/community',
         'kubevirt/kubevirt',
         ...
       )
    on conflict update;

-- 2)
insert into gha_repo_groups(id, name, repo_group, alias, org_id, org_login)
     select id, name, 'sig-documentation', alias, org_id, org_login 
       from gha_repo_groups
      where lower(name) in (
              'kubevirt/kubevirt.github.io',
              'kubevirt/kubevirt',
              ...
            )
on conflict update;

...

-- for the remaining rows where the repo_group has not been touched we set the default "Other"

UPDATE gha_repos
   SET repo_group = 'Other'
 WHERE repo_group = alias

```

This would assume generating it from our [`sigs.yaml`](https://github.com/kubevirt/community/blob/main/sigs.yaml)

Would that work?

**Comment by lukaszgryglicki** [comment]
Yes, this will work. I will of course check thid one PR is ready, so I can see the real output it creates.

**Comment by dhiller** [comment]
@lukaszgryglicki I have created https://github.com/cncf/devstats/pull/77 from the code of the above mentioned PR. Would you mind taking a look whether that works? Thank you!

**Comment by lukaszgryglicki** [comment]
https://github.com/cncf/devstats/pull/77#issuecomment-2407747296

**Comment by lukaszgryglicki** [comment]
Update: https://github.com/cncf/devstats/pull/77#issuecomment-2410253695.

**Comment by lukaszgryglicki** [comment]
This needs feedback (regarding what should I track) @dhiller https://github.com/cncf/devstats/pull/77#issuecomment-2410285935.

Also pls update your automatic tool to update repo groups for kubevirt to match this syntax: https://github.com/cncf/devstats/blob/master/scripts/kubevirt/repo_groups.sql - especially [this](https://github.com/cncf/devstats/blob/master/scripts/kubevirt/repo_groups.sql#L43-L99) part which defines all repos-repo- groups mapping.

**Comment by lukaszgryglicki** [comment]
FYI: https://github.com/cncf/devstats/pull/77#issuecomment-2410469744.
